# Generated by Django 3.1.7 on 2021-03-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('formation', models.CharField(max_length=600)),
                ('langue', models.CharField(max_length=200)),
                ('profil', models.CharField(max_length=600)),
                ('experience', models.CharField(max_length=600)),
                ('competence', models.CharField(max_length=600)),
            ],
        ),
    ]
